import Head from "next/head";
import React from "react";
import Footer from "../Shared/Footer";
import Header from "../Shared/Header";

const Layout = ({ title, children }) => {
	return (
		<>
			<Head>
				<title>{title || "Keya Cosmetics"}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="description" content="An e-commerce project" />
				<meta name="author" content="Md. Lutfor Rahman" />

				<meta
					name="viewport"
					content="width=device-width, initial-scale=1, maximum-scale=1"
				/>
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />

				{/* fab icon */}
				<link rel="icon" href="/logo.png" type="image/x-icon" />
				<link rel="shortcut icon" href="/logo.png" type="image/x-icon" />
			</Head>

			<Header />

			<main>{children}</main>

			<Footer />
		</>
	);
};

export default Layout;
